name: Noarr test ubuntu-latest

on:
  push:
    paths:
    - 'include/**'
    - 'tests/**'
    - '.github/workflows/noarr_test_ubuntul.yml'

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        os: [ubuntu-latest]
        BUILD_TYPE: [Debug, Release]
        compiler: [g++-10, g++-11, g++-12, g++-13, clang++-14, clang++-15]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            install: sudo apt update && sudo apt install g++-10
          - os: ubuntu-latest
            compiler: g++-11
            install: sudo apt update && sudo apt install g++-11
          - os: ubuntu-latest
            compiler: g++-12
            install: sudo apt update && sudo apt install g++-12
          - os: ubuntu-latest
            compiler: g++-13
            install: sudo apt update && sudo apt install g++-13
          - os: ubuntu-latest
            compiler: clang++-14
            install: sudo apt update && sudo apt install clang-14
          - os: ubuntu-latest
            compiler: clang++-15
            install: sudo apt update && sudo apt install clang-15
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install compiler
      shell: bash
      run: ${{ matrix.install }}

    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}/tests
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/tests/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake .. -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

    - name: Build
      working-directory: ${{github.workspace}}/tests/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config ${{matrix.BUILD_TYPE}} -j

    - name: Test
      working-directory: ${{github.workspace}}/tests/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -V -C ${{matrix.BUILD_TYPE}}
