name: Noarr Tuning Opentuner test ubuntu-latest

on:
  push:
    paths:
    - 'include/**'
    - 'tests/opentuner_test/**'
    - '.github/workflows/opentuner_test_ubuntul.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        BUILD_TYPE: [Debug, Release]
        compiler: [g++-10, g++-11, g++-12, g++-13]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            install: sudo apt update && sudo apt install g++-10 python3 python3-pip python3-virtualenv
          - os: ubuntu-latest
            compiler: g++-11
            install: sudo apt update && sudo apt install g++-11 python3 python3-pip python3-virtualenv
          - os: ubuntu-latest
            compiler: g++-12
            install: sudo apt update && sudo apt install g++-12 python3 python3-pip python3-virtualenv
          - os: ubuntu-latest
            compiler: g++-13
            install: sudo apt update && sudo apt install g++-13 python3 python3-pip python3-virtualenv
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      shell: bash
      run: ${{ matrix.install }}

    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}/tests/opentuner_test
      run: |
        source prepare_env.sh
        cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/tests/opentuner_test/build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

    - name: Build
      working-directory: ${{github.workspace}}/tests/opentuner_test
      shell: bash
      run: |
        source prepare_env.sh
        cmake --build build --config ${{matrix.BUILD_TYPE}} -j$(nproc)

    - name: Tune
      working-directory: ${{github.workspace}}/tests/opentuner_test
      shell: bash
      run: |
        source prepare_env.sh
        cd build
        python3 <(./opentuner_test_cmake) --test-limit=20 --no-dups
